version: "3"

services:
    HostA:
        image: handsonsecurity/seed-ubuntu:large # custom image used to create the containers
        container_name: A-10.9.0.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        command: bash -c "
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null"

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

